# Generated by Django 4.2.6 on 2023-11-08 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercl',
            name='order_select',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_object', to='cloth.productcl'),
            preserve_default=False,
        ),
    ]
