# Generated by Django 4.2.6 on 2023-11-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0002_ordercl_order_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercl',
            name='order',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
