# Generated by Django 4.2.6 on 2023-11-08 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0003_ordercl_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercl',
            name='order',
        ),
    ]
